<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Arlecchino.Tools</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Arlecchino.Testing/Arlecchino.Testing.csproj" />
  </ItemGroup>

</Project>
