using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arlecchino.Generators;

[Generator]
public sealed class CommandRegistrationGenerator : IIncrementalGenerator
{
    private const string CommandInterfaceNamespace = "Arlecchino.Commands";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settings = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.ArlecchinoGenerateCommands", out var enabled);
            provider.GlobalOptions.TryGetValue("build_property.ArlecchinoViewNamespace", out var viewNamespace);
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);

            var generate = string.IsNullOrEmpty(enabled) ||
                           !string.Equals(enabled, "false", StringComparison.OrdinalIgnoreCase);

            if (string.IsNullOrEmpty(viewNamespace))
            {
                viewNamespace = string.IsNullOrEmpty(rootNamespace)
                    ? "Views"
                    : rootNamespace + ".Navigation";
            }

            return new Settings(generate, viewNamespace!);
        });

        var commandDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => GetCommand(ctx))
            .Where(static command => command != null);

        context.RegisterSourceOutput(commandDeclarations.Collect().Combine(settings), static (ctx, pair) =>
        {
            var (commands, settings) = pair;
            if (!settings.Generate)
            {
                return;
            }

            var commandModels = commands
                .OfType<CommandModel>()
                .OrderBy(static command => command.TypeName, StringComparer.Ordinal)
                .ToArray();

            foreach (var command in commandModels)
            {
                if (!command.HasPublicConstructor)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        CommandDiagnostics.NoPublicConstructor, command.Location, command.TypeName));
                }
            }

            ctx.AddSource("ArlecchinoCommandRegistration.g.cs",
                SourceText.From(Generate(commandModels, settings.CommandNamespace), Encoding.UTF8));
        });
    }

    private static CommandModel? GetCommand(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || !Implements(symbol))
        {
            return null;
        }

        var typeName = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var containingNamespace = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();
        var hasPublicConstructor = symbol.InstanceConstructors
            .Any(static item => item.DeclaredAccessibility == Accessibility.Public);

        return new(
            typeName,
            containingNamespace,
            ConstructorBinding.Of(symbol),
            hasPublicConstructor,
            declaration.Identifier.GetLocation());
    }

    private static bool Implements(INamedTypeSymbol symbol)
    {
        return symbol.AllInterfaces.Any(static item =>
            item.Name == "IArlecchinoCommand" &&
            item.ContainingNamespace.ToDisplayString() == CommandInterfaceNamespace);
    }

    private static string Generate(IReadOnlyList<CommandModel> commands, string commandNamespace)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("using Arlecchino.Commands;");
        builder.AppendLine("using Arlecchino.Hosting;");

        foreach (var namespaceName in commands
                     .SelectMany(static command => command.ConstructorParameters
                         .Select(static parameter => parameter.Namespace)
                         .Concat([command.Namespace]))
                     .Where(namespaceName => namespaceName.Length > 0 &&
                                             namespaceName != "Microsoft.Extensions.DependencyInjection" &&
                                             namespaceName != "Arlecchino.Commands" &&
                                             namespaceName != "Arlecchino.Hosting" &&
                                             namespaceName != commandNamespace)
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(static namespaceName => namespaceName, StringComparer.Ordinal))
        {
            builder.Append("using ").Append(namespaceName).AppendLine(";");
        }

        builder.AppendLine();
        builder.Append("namespace ").Append(commandNamespace).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedCommandRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    public static ArlecchinoBuilder AddGeneratedCommands(this ArlecchinoBuilder builder)");
        builder.AppendLine("    {");

        foreach (var command in commands)
        {
            builder.Append("        builder.Services.AddSingleton<IArlecchinoCommand>(static services => ")
                .Append(ConstructorBinding.CreateExpression(command.TypeName, command.ConstructorParameters))
                .AppendLine(");");
        }

        builder.AppendLine("        return builder;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private sealed class Settings
    {
        public Settings(bool generate, string commandNamespace)
        {
            Generate = generate;
            CommandNamespace = commandNamespace;
        }

        public bool Generate { get; }
        public string CommandNamespace { get; }
    }

    private sealed class CommandModel
    {
        public CommandModel(
            string typeName,
            string @namespace,
            IReadOnlyList<ParameterModel> constructorParameters,
            bool hasPublicConstructor,
            Location location)
        {
            TypeName = typeName;
            Namespace = @namespace;
            ConstructorParameters = constructorParameters;
            HasPublicConstructor = hasPublicConstructor;
            Location = location;
        }

        public string TypeName { get; }
        public string Namespace { get; }
        public IReadOnlyList<ParameterModel> ConstructorParameters { get; }
        public bool HasPublicConstructor { get; }
        public Location Location { get; }
    }
}
