using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Arlecchino.Generators;

public sealed partial class LocalizationGenerator
{
    /// <summary>
    /// Writes the enum of names and the function that resolves them. A string is a <c>switch</c> arm rather
    /// than a dictionary entry, since the set is closed at compile time.
    /// </summary>
    /// <param name="where">The namespace to put it in.</param>
    /// <param name="standard">The default localization.</param>
    /// <param name="localizations">Every localization, the default included.</param>
    /// <returns>The source to compile.</returns>
    private static string BuildSource(
        string where,
        LocalizationFile standard,
        IReadOnlyList<LocalizationFile> localizations)
    {
        var translations = localizations
            .Where(localization => !ReferenceEquals(localization, standard))
            .OrderBy(static localization => localization.Language, StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.Globalization;");
        source.AppendLine("using Arlecchino.Commands;");
        source.AppendLine("using Arlecchino.Input;");
        source.AppendLine("using Arlecchino.Navigation;");
        source.AppendLine();
        source.Append("namespace ").Append(where).AppendLine(";");
        source.AppendLine();
        source.AppendLine("/// <summary>Every piece of text this application draws, by name.</summary>");
        source.AppendLine("public enum LocString : ushort");
        source.AppendLine("{");

        for (var index = 0; index < standard.Entries.Count; index++)
        {
            source.Append("    /// <summary><c>")
                .Append(Commented(standard.Entries[index].Value))
                .AppendLine("</c></summary>");
            source.Append("    ").Append(standard.Entries[index].Key).Append(" = ").Append(index).AppendLine(",");
        }

        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("/// <summary>Resolves a <see cref=\"LocString\"/> to the text behind it.</summary>");
        source.AppendLine("public static class Localization");
        source.AppendLine("{");
        source.Append("    private const string Standard = ").Append(Quote(standard.Language)).AppendLine(";");
        source.AppendLine();
        source.AppendLine("    /// <summary>The languages there is text for.</summary>");
        source.Append("    public static IReadOnlyList<string> Languages { get; } = new[] { ")
            .Append(string.Join(", ",
                localizations
                    .Select(static localization => localization.Language)
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(static language => language, StringComparer.Ordinal)
                    .Select(Quote)))
            .AppendLine(" };");
        source.AppendLine();
        source.AppendLine("    /// <summary>Which one is being drawn, taken from the machine's own setting.</summary>");
        source.AppendLine("    public static string Language { get; set; } = Nearest(CultureInfo.CurrentUICulture.Name);");
        source.AppendLine();
        source.AppendLine("    /// <summary>The text behind a name.</summary>");
        source.AppendLine("    /// <param name=\"key\">Which text.</param>");
        source.AppendLine("    /// <returns>The text.</returns>");
        source.AppendLine("    public static string Loc(LocString key) => Resolve(key);");
        source.AppendLine();
        source.AppendLine("    /// <summary>The text behind a name, with what belongs in it filled in.</summary>");
        source.AppendLine("    /// <param name=\"key\">Which text.</param>");
        source.AppendLine("    /// <param name=\"arguments\">What goes in its placeholders.</param>");
        source.AppendLine("    /// <returns>The text.</returns>");
        source.AppendLine("    public static string Loc(LocString key, params object?[] arguments) =>");
        source.AppendLine("        string.Format(CultureInfo.CurrentCulture, Resolve(key), arguments);");
        source.AppendLine();
        source.AppendLine("    private static string Resolve(LocString key)");
        source.AppendLine("    {");

        if (translations.Length > 0)
        {
            source.AppendLine("        var said = Language switch");
            source.AppendLine("        {");

            foreach (var translation in translations)
            {
                source.Append("            ")
                    .Append(Quote(translation.Language))
                    .Append(" => ")
                    .Append(MethodFor(translation.Language))
                    .AppendLine("(key),");
            }

            source.AppendLine("            _ => null,");
            source.AppendLine("        };");
            source.AppendLine();
            source.AppendLine("        return said ?? Standard_(key);");
        }
        else
        {
            source.AppendLine("        return Standard_(key);");
        }

        source.AppendLine("    }");
        source.AppendLine();

        Table(source, "Standard_", standard.Entries, false);

        foreach (var translation in translations)
        {
            source.AppendLine();
            Table(source, MethodFor(translation.Language), translation.Entries, true);
        }

        source.AppendLine();
        source.AppendLine("    /// <summary>The closest language there is text for, falling back to the default.</summary>");
        source.AppendLine("    /// <param name=\"wanted\">What the machine asked for.</param>");
        source.AppendLine("    /// <returns>The one to draw in.</returns>");
        source.AppendLine("    public static string Nearest(string? wanted)");
        source.AppendLine("    {");
        source.AppendLine("        if (string.IsNullOrWhiteSpace(wanted))");
        source.AppendLine("        {");
        source.AppendLine("            return Standard;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var asked = wanted!.Replace('_', '-').ToLowerInvariant();");
        source.AppendLine("        var dash = asked.IndexOf('-');");
        source.AppendLine("        var bare = dash >= 0 ? asked.Substring(0, dash) : asked;");
        source.AppendLine();
        source.AppendLine("        foreach (var language in Languages)");
        source.AppendLine("        {");
        source.AppendLine("            if (language.Equals(asked, StringComparison.OrdinalIgnoreCase) ||");
        source.AppendLine("                language.Equals(bare, StringComparison.OrdinalIgnoreCase))");
        source.AppendLine("            {");
        source.AppendLine("                return language;");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return Standard;");
        source.AppendLine("    }");
        source.AppendLine("}");

        Bindings(source);

        return source.ToString();
    }

    /// <summary>
    /// Writes the factories that name a key from the localization. The framework cannot ship them itself,
    /// since the enum they take is written here out of the application's own files.
    /// </summary>
    /// <param name="source">Where the source is being built.</param>
    private static void Bindings(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("/// <summary>A key of this application, named from its own localization.</summary>");
        source.AppendLine("public static class Bind");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>A key that does something and stays on the screen.</summary>");
        source.AppendLine("    /// <param name=\"binding\">The key.</param>");
        source.AppendLine("    /// <param name=\"name\">Which string names it.</param>");
        source.AppendLine("    /// <param name=\"run\">What it does.</param>");
        source.AppendLine("    /// <returns>The command.</returns>");
        source.AppendLine("    public static ViewCommand To(KeyBinding binding, LocString name, Action run) =>");
        source.AppendLine("        ViewCommand.For(binding, () => Localization.Loc(name), run);");
        source.AppendLine();
        source.AppendLine("    /// <summary>A key that leaves the screen.</summary>");
        source.AppendLine("    /// <param name=\"binding\">The key.</param>");
        source.AppendLine("    /// <param name=\"name\">Which string names it.</param>");
        source.AppendLine("    /// <param name=\"run\">Where it goes.</param>");
        source.AppendLine("    /// <returns>The command.</returns>");
        source.AppendLine("    public static ViewCommand Going(");
        source.AppendLine("        KeyBinding binding, LocString name, Func<ViewRoute> run) => new()");
        source.AppendLine("    {");
        source.AppendLine("        Binding = binding,");
        source.AppendLine("        Label = () => Localization.Loc(name),");
        source.AppendLine("        Run = run,");
        source.AppendLine("    };");
        source.AppendLine();
        source.AppendLine("    /// <summary>A key that is only sometimes available.</summary>");
        source.AppendLine("    /// <param name=\"binding\">The key.</param>");
        source.AppendLine("    /// <param name=\"name\">Which string names it.</param>");
        source.AppendLine("    /// <param name=\"enabled\">Whether it can run now.</param>");
        source.AppendLine("    /// <param name=\"run\">What it does.</param>");
        source.AppendLine("    /// <returns>The command.</returns>");
        source.AppendLine("    public static ViewCommand When(");
        source.AppendLine("        KeyBinding binding, LocString name, Func<bool> enabled, Func<ViewRoute> run) => new()");
        source.AppendLine("    {");
        source.AppendLine("        Binding = binding,");
        source.AppendLine("        Label = () => Localization.Loc(name),");
        source.AppendLine("        IsEnabled = enabled,");
        source.AppendLine("        Run = run,");
        source.AppendLine("    };");
        source.AppendLine("}");
    }

    private static void Table(
        StringBuilder source,
        string method,
        IReadOnlyList<LocalizationEntry> entries,
        bool partial)
    {
        source.Append("    private static string")
            .Append(partial ? "? " : " ")
            .Append(method)
            .AppendLine("(LocString key) => key switch");
        source.AppendLine("    {");

        foreach (var entry in entries)
        {
            source.Append("        LocString.")
                .Append(entry.Key)
                .Append(" => ")
                .Append(Quote(entry.Value))
                .AppendLine(",");
        }

        source.AppendLine(partial ? "        _ => null," : "        _ => key.ToString(),");
        source.AppendLine("    };");
    }

    private static string MethodFor(string language)
    {
        var method = new StringBuilder("In_");

        foreach (var character in language)
        {
            method.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return method.ToString();
    }

    private static string Commented(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;")
        .Replace("\r", " ")
        .Replace("\n", " ");

    private static string Quote(string value) => "\"" +
                                                 value
                                                     .Replace("\\", "\\\\")
                                                     .Replace("\"", "\\\"")
                                                     .Replace("\r", "\\r")
                                                     .Replace("\n", "\\n")
                                                     .Replace("\t", "\\t") +
                                                 "\"";
}
