using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arlecchino.Generators;

[Generator]
public sealed class StoreRegistrationGenerator : IIncrementalGenerator
{
    private const string StoreInterfaceNamespace = "Arlecchino.Atoms";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settings = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.ArlecchinoGenerateStores", out var enabled);
            provider.GlobalOptions.TryGetValue("build_property.ArlecchinoViewNamespace", out var viewNamespace);
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);

            var generate = string.IsNullOrEmpty(enabled) ||
                           !string.Equals(enabled, "false", StringComparison.OrdinalIgnoreCase);

            if (string.IsNullOrEmpty(viewNamespace))
            {
                viewNamespace = string.IsNullOrEmpty(rootNamespace)
                    ? "Views"
                    : rootNamespace + ".Navigation";
            }

            return new Settings(generate, viewNamespace!);
        });

        var storeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => GetStore(ctx))
            .Where(static store => store != null);

        context.RegisterSourceOutput(storeDeclarations.Collect().Combine(settings),
            static (ctx, pair) =>
            {
                var (stores, settings) = pair;
                if (!settings.IsEnabled)
                {
                    return;
                }

                var storeModels = stores
                    .OfType<StoreModel>()
                    .OrderBy(static store => store.TypeName, StringComparer.Ordinal)
                    .ToArray();

                foreach (var store in storeModels)
                {
                    if (!store.HasPublicConstructor)
                    {
                        ctx.ReportDiagnostic(Diagnostic.Create(
                            StoreDiagnostics.NoPublicConstructor,
                            store.Location,
                            store.TypeName));
                    }
                }

                var registrable = storeModels.Where(static store => store.HasPublicConstructor).ToArray();

                ctx.AddSource("ArlecchinoStoreRegistration.g.cs",
                    SourceText.From(Generate(registrable, settings.StoreNamespace), Encoding.UTF8));
            });
    }

    private static StoreModel? GetStore(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || !TypeNames.IsReachable(symbol) || !Implements(symbol, "IArlecchinoStore"))
        {
            return null;
        }

        var typeName = TypeNames.Of(symbol);
        var containingNamespace = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();
        var hasPublicConstructor = symbol.InstanceConstructors
            .Any(static item => item.DeclaredAccessibility == Accessibility.Public);

        return new(
            typeName,
            containingNamespace,
            Implements(symbol, "IArlecchinoScopedStore"),
            Inherits(symbol, "ArlecchinoAsyncStore"),
            ConstructorBinding.Of(symbol),
            hasPublicConstructor,
            declaration.Identifier.GetLocation());
    }

    private static bool Inherits(INamedTypeSymbol symbol, string baseName)
    {
        for (var current = symbol.BaseType; current is not null; current = current.BaseType)
        {
            if (current.Name == baseName && current.ContainingNamespace.ToDisplayString() == StoreInterfaceNamespace)
            {
                return true;
            }
        }

        return false;
    }

    private static bool Implements(INamedTypeSymbol symbol, string interfaceName)
    {
        return symbol.AllInterfaces.Any(item =>
            item.Name == interfaceName &&
            item.ContainingNamespace.ToDisplayString() == StoreInterfaceNamespace);
    }

    private static string Generate(IReadOnlyList<StoreModel> stores, string storeNamespace)
    {
        return $$"""
                 // <auto-generated/>
                 #nullable enable
                 using Microsoft.Extensions.DependencyInjection;
                 using Arlecchino.Hosting;{{Imports(stores, storeNamespace)}}

                 namespace {{storeNamespace}};

                 public static class GeneratedStoreRegistration
                 {
                     public static ArlecchinoBuilder AddGeneratedStores(this ArlecchinoBuilder builder)
                     {
                 {{Body(stores)}}
                     }
                 }

                 """;
    }

    /// <summary>
    /// The namespaces the generated file needs beyond the ones it always writes. Each is led by a
    /// newline rather than followed by one, so that none of them leaves a blank line behind.
    /// </summary>
    /// <param name="stores">The stores being registered.</param>
    /// <param name="storeNamespace">Where the generated file itself lives.</param>
    /// <returns>The lines, or an empty string.</returns>
    private static string Imports(IReadOnlyList<StoreModel> stores, string storeNamespace)
    {
        var names = stores
            .SelectMany(static store => store.ConstructorParameters
                .Select(static parameter => parameter.Namespace)
                .Concat([store.Namespace]))
            .Where(namespaceName => namespaceName.Length > 0 &&
                                    namespaceName != "Microsoft.Extensions.DependencyInjection" &&
                                    namespaceName != "Arlecchino.Hosting" &&
                                    namespaceName != storeNamespace)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static namespaceName => namespaceName, StringComparer.Ordinal)
            .Select(static namespaceName => $"using {namespaceName};");

        return string.Concat(names.Select(static line => "\n" + line));
    }

    private static string Body(IReadOnlyList<StoreModel> stores)
    {
        var registrations = stores.SelectMany(static store => Registration(store));

        return string.Join("\n", (string[])[.. registrations, "        return builder;"]);
    }

    private static IEnumerable<string> Registration(StoreModel store)
    {
        var lifetime = store.IsScoped ? "Scoped" : "Singleton";
        var created = ConstructorBinding.CreateExpression(store.TypeName, store.ConstructorParameters);

        yield return $"        builder.Services.Add{lifetime}(static services => {created});";

        if (!store.IsAsync || store.IsScoped)
        {
            yield break;
        }

        yield return
            "        builder.Services.AddSingleton<global::Arlecchino.Atoms.ArlecchinoAsyncStore>(" +
            $"static services => services.GetRequiredService<{store.TypeName}>());";
    }

    private sealed class Settings
    {
        public Settings(bool generate, string storeNamespace)
        {
            IsEnabled = generate;
            StoreNamespace = storeNamespace;
        }

        public bool IsEnabled { get; }
        public string StoreNamespace { get; }
    }

    private sealed class StoreModel
    {
        public StoreModel(
            string typeName,
            string @namespace,
            bool isScoped,
            bool isAsync,
            IReadOnlyList<ParameterModel> constructorParameters,
            bool hasPublicConstructor,
            Location location)
        {
            TypeName = typeName;
            Namespace = @namespace;
            IsScoped = isScoped;
            IsAsync = isAsync;
            ConstructorParameters = constructorParameters;
            HasPublicConstructor = hasPublicConstructor;
            Location = location;
        }

        public string TypeName { get; }
        public string Namespace { get; }
        public bool IsScoped { get; }
        public bool IsAsync { get; }
        public IReadOnlyList<ParameterModel> ConstructorParameters { get; }
        public bool HasPublicConstructor { get; }
        public Location Location { get; }
    }
}
