using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arlecchino.Generators;

[Generator]
public sealed class StoreRegistrationGenerator : IIncrementalGenerator
{
    private const string StoreInterfaceNamespace = "Arlecchino.Atoms";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settings = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.ArlecchinoGenerateStores", out var enabled);
            provider.GlobalOptions.TryGetValue("build_property.ArlecchinoViewNamespace", out var viewNamespace);
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);

            var generate = string.IsNullOrEmpty(enabled) ||
                           !string.Equals(enabled, "false", StringComparison.OrdinalIgnoreCase);

            if (string.IsNullOrEmpty(viewNamespace))
            {
                viewNamespace = string.IsNullOrEmpty(rootNamespace)
                    ? "Views"
                    : rootNamespace + ".Navigation";
            }

            return new Settings(generate, viewNamespace!);
        });

        var storeDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => GetStore(ctx))
            .Where(static store => store != null);

        context.RegisterSourceOutput(storeDeclarations.Collect().Combine(settings), static (ctx, pair) =>
        {
            var (stores, settings) = pair;
            if (!settings.IsEnabled)
            {
                return;
            }

            var storeModels = stores
                .OfType<StoreModel>()
                .OrderBy(static store => store.TypeName, StringComparer.Ordinal)
                .ToArray();

            foreach (var store in storeModels)
            {
                if (!store.HasPublicConstructor)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        StoreDiagnostics.NoPublicConstructor, store.Location, store.TypeName));
                }
            }

            var registrable = storeModels.Where(static store => store.HasPublicConstructor).ToArray();

            ctx.AddSource("ArlecchinoStoreRegistration.g.cs",
                SourceText.From(Generate(registrable, settings.StoreNamespace), Encoding.UTF8));
        });
    }

    private static StoreModel? GetStore(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || !TypeNames.IsReachable(symbol) || !Implements(symbol, "IArlecchinoStore"))
        {
            return null;
        }

        var typeName = TypeNames.Of(symbol);
        var containingNamespace = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();
        var hasPublicConstructor = symbol.InstanceConstructors
            .Any(static item => item.DeclaredAccessibility == Accessibility.Public);

        return new(
            typeName,
            containingNamespace,
            Implements(symbol, "IArlecchinoScopedStore"),
            ConstructorBinding.Of(symbol),
            hasPublicConstructor,
            declaration.Identifier.GetLocation());
    }

    private static bool Implements(INamedTypeSymbol symbol, string interfaceName)
    {
        return symbol.AllInterfaces.Any(item =>
            item.Name == interfaceName &&
            item.ContainingNamespace.ToDisplayString() == StoreInterfaceNamespace);
    }

    private static string Generate(IReadOnlyList<StoreModel> stores, string storeNamespace)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("using Arlecchino.Hosting;");

        foreach (var namespaceName in stores
                     .SelectMany(static store => store.ConstructorParameters
                         .Select(static parameter => parameter.Namespace)
                         .Concat([store.Namespace]))
                     .Where(namespaceName => namespaceName.Length > 0 &&
                                             namespaceName != "Microsoft.Extensions.DependencyInjection" &&
                                             namespaceName != "Arlecchino.Hosting" &&
                                             namespaceName != storeNamespace)
                     .Distinct(StringComparer.Ordinal)
                     .OrderBy(static namespaceName => namespaceName, StringComparer.Ordinal))
        {
            builder.Append("using ").Append(namespaceName).AppendLine(";");
        }

        builder.AppendLine();
        builder.Append("namespace ").Append(storeNamespace).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedStoreRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    public static ArlecchinoBuilder AddGeneratedStores(this ArlecchinoBuilder builder)");
        builder.AppendLine("    {");

        foreach (var store in stores)
        {
            builder.Append("        builder.Services.Add").Append(store.IsScoped ? "Scoped" : "Singleton")
                .Append("(static services => ")
                .Append(ConstructorBinding.CreateExpression(store.TypeName, store.ConstructorParameters))
                .AppendLine(");");
        }

        builder.AppendLine("        return builder;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private sealed class Settings
    {
        public Settings(bool generate, string storeNamespace)
        {
            IsEnabled = generate;
            StoreNamespace = storeNamespace;
        }

        public bool IsEnabled { get; }
        public string StoreNamespace { get; }
    }

    private sealed class StoreModel
    {
        public StoreModel(
            string typeName,
            string @namespace,
            bool isScoped,
            IReadOnlyList<ParameterModel> constructorParameters,
            bool hasPublicConstructor,
            Location location)
        {
            TypeName = typeName;
            Namespace = @namespace;
            IsScoped = isScoped;
            ConstructorParameters = constructorParameters;
            HasPublicConstructor = hasPublicConstructor;
            Location = location;
        }

        public string TypeName { get; }
        public string Namespace { get; }
        public bool IsScoped { get; }
        public IReadOnlyList<ParameterModel> ConstructorParameters { get; }
        public bool HasPublicConstructor { get; }
        public Location Location { get; }
    }
}
